version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: php8-nginx
    ports:
      - "9000:80"
    depends_on:
      - php-fpm
    volumes:
      - ./public:/var/www/html:ro
    networks:
      - app-network
    restart: unless-stopped

  php-fpm:
    build: ./php-fpm
    container_name: php8-fpm
    volumes:
      - ./public:/var/www/html
    networks:
      - app-network
    environment:
      - REDIS_HOST=192.168.99.7
      - REDIS_PORT=6379
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
